scene.onOverlapTile(SpriteKind.Player, assets.tile`d`, function (sprite, location) {
	
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d6`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    info.changeLifeBy(-100)
    mySprite.say("阿", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖1`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`告示牌0`, function (sprite, location) {
    game.splash("你來了阿", "你要的東西在前面")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`磚塊1`, function (sprite, location) {
    mySprite.say("三小", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gold粉紅顛倒0`, function (sprite, location) {
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`cup0`, function (sprite, location) {
    scene.setBackgroundColor(0)
    tiles.setTilemap(tilemap`層級5`)
    tiles.placeOnRandomTile(mySprite, assets.tile`cup`)
    tiles.placeOnRandomTile(妖精1, assets.tile`cup4`)
    tiles.placeOnRandomTile(妖精2, assets.tile`cup4`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`cup4`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`cup4`)
    tiles.placeOnRandomTile(章魚, assets.tile`cup4`)
    tiles.placeOnRandomTile(章魚2, assets.tile`cup4`)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(assets.image`波`, mySprite, -100, 0)
    mySprite.say("Expelliarmus", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖6`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣4`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級14`)
    tiles.placeOnRandomTile(mySprite, assets.tile`myTile12`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣2`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級12`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`門`, function (sprite, location) {
    tiles.setTilemap(tilemap`層級2`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    scene.setBackgroundColor(2)
    tiles.placeOnRandomTile(妖精1, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚2, sprites.swamp.swampTile2)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`磚塊3`, function (sprite, location) {
    mySprite.say("感覺到怪怪的", 200)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d0`, function (sprite, location) {
    tiles.setTilemap(tilemap`層級1`)
    scene.setBackgroundColor(7)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚2, sprites.swamp.swampTile2)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣1`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級11`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.forestTiles12, function (sprite, location) {
    mySprite.say("我感受到力量", 500)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    sprite.destroy(effects.fire, 200)
    otherSprite.destroy(effects.halo, 100)
    scene.cameraShake(2, 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d3`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    info.changeLifeBy(-100)
    mySprite.say("好痛", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`ten1`, function (sprite, location) {
    scene.setBackgroundColor(7)
    tiles.setTilemap(tilemap`層級10`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚2, sprites.dungeon.hazardLava1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`珍珠陷阱`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級18`)
    tiles.placeOnRandomTile(mySprite, assets.tile`0`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
    game.splash("我希望你的生命還扛住這個", "勇者")
    pause(100)
    game.splash("你想要的東西就在前面", "你去拿吧")
    pause(100)
    game.splash("不過", "代價不小")
    pause(100)
    game.splash("請務必考慮清楚", "再會")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖2`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`cup3`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`主要地圖 珍珠`)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.oceanDepths9)
    妖精1.setPosition(73, 195)
    妖精2.setPosition(43, 152)
    妖精藍.setPosition(248, 23)
    妖精藍2.setPosition(229, 10)
    章魚.setPosition(110, 200)
    章魚2.setPosition(120, 250)
    game.splash("剛剛那個太恐怖了", "怎麼利用法力變出如此多的杯子")
    pause(100)
    game.splash("還不小心被傳回來了", "希望有吸收全部法力阿")
    pause(100)
    game.splash("嗯?", "他消失了嗎")
    pause(100)
    game.splash("恩", "杯子那麼多太可怕了")
    pause(100)
    game.splash("恩", "杯子那麼多太可怕了")
    pause(100)
    game.splash("所以說", "有些東西不要太多或太少就是最完美的時候")
    pause(100)
    game.splash("所以說", "一個老婆才是最幸福的時候")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣5`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級15`)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`大法師`, function (sprite, location) {
    tiles.setTilemap(tilemap`層級43`)
    scene.setBackgroundImage(assets.image`怪盜團0`)
    pause(100)
    game.splash("你好", "我是凌波零")
    pause(100)
    game.splash("我是迷宮跟寶物", "的主人")
    pause(100)
    game.splash("勇者恭喜你", "你已經收集了")
    pause(100)
    game.splash("五個魔力", "最強大的聖物")
    pause(100)
    game.splash("你通過了", "我設計的關卡")
    pause(100)
    game.splash("並勇往直前")
    pause(100)
    game.splash("我很欣賞你")
    pause(100)
    game.splash("希望你好好的利用", "這股強大的力量")
    pause(100)
    game.splash("再會了")
    pause(100)
    game.splash("員工名單")
    pause(100)
    game.splash("戴宇輝", "林憶廷")
    pause(100)
    game.splash("宇輝出品", "必是精品")
    pause(100)
    game.over(true, effects.starField)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣3`, function (sprite, location) {
    mySprite.setImage(assets.image`CAR`)
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級13`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊1`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`告示牌`, function (sprite, location) {
    game.splash("讚石在那", "去拿吧勇者")
    pause(500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gold劍柄是皮膚色 本尊`, function (sprite, location) {
    info.changeScoreBy(12)
    tiles.setTileAt(location, assets.tile`transparency16`)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`ten`, function (sprite, location) {
    info.changeScoreBy(102)
    tiles.setTileAt(location, sprites.builtin.oceanDepths9)
    tiles.setTilemap(tilemap`主要地圖 都沒有`)
    scene.setBackgroundColor(15)
    tiles.placeOnRandomTile(mySprite, assets.tile`往前走`)
    妖精1.setPosition(73, 195)
    妖精2.setPosition(43, 152)
    妖精藍.setPosition(248, 23)
    妖精藍2.setPosition(229, 10)
    章魚.setPosition(110, 200)
    章魚2.setPosition(120, 250)
    info.changeLifeBy(102)
    game.splash("這東西", "法力怎麼這模強")
    pause(100)
    game.splash("我還變成車", "還好有變回來")
    pause(100)
    game.splash("我老婆還在家等我呢", "我好想他")
    pause(100)
    game.splash("搞這一趟", "已經有2個月沒有看到他了")
    pause(100)
    game.splash("如果可以用我的法力", "跟他說我愛他就好了..")
    pause(100)
    game.splash("我愛你", "雖然你聽不到")
    pause(100)
    game.splash("我愛你", "還是其實你聽的到呢?")
    pause(100)
    game.splash("雖然沒有辦法見面", "不過我心與你同在")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d1`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`transparency16`)
    info.changeLifeBy(-100)
    mySprite.say("這裡怎麼怪怪的", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gold陷阱`, function (sprite, location) {
    tiles.setTilemap(tilemap`黃金劍地圖1`)
    scene.setBackgroundColor(3)
    tiles.placeOnRandomTile(mySprite, assets.tile`gold粉紅0`)
    tiles.placeOnRandomTile(妖精1, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚2, sprites.dungeon.hazardLava1)
    scene.setBackgroundImage(assets.tile`磚塊`)
    game.splash("小心走路 ", "當心腳下")
    game.splash("找到白色劍柄的劍", "與找到出口")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gold劍柄是皮膚色 本尊0`, function (sprite, location) {
    game.splash("你認為這是出口?", "在細心一點")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖4`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(assets.image`波2`, mySprite, 100, 0)
    mySprite.say("Avada Kedavra", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
    mySprite.say("感覺到怪怪的", 200)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`gold劍柄是皮膚色`, function (sprite, location) {
    tiles.setTilemap(tilemap`主要地圖 鑽石`)
    scene.setBackgroundColor(15)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.oceanDepths9)
    妖精1.setPosition(73, 195)
    妖精2.setPosition(43, 152)
    妖精藍.setPosition(248, 23)
    妖精藍2.setPosition(229, 10)
    章魚.setPosition(110, 200)
    章魚2.setPosition(120, 250)
    info.changeScoreBy(10)
    info.changeLifeBy(100)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣6`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級16`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊2`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`往前走`, function (sprite, location) {
    mySprite.say("嗯?那是誰", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`cup傳送觸發`, function (sprite, location) {
    scene.setBackgroundColor(6)
    tiles.setTilemap(tilemap`層級3`)
    tiles.placeOnRandomTile(mySprite, assets.tile`杯子地圖主角傳送方塊`)
    tiles.placeOnRandomTile(妖精1, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(妖精藍2, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚, sprites.dungeon.hazardLava1)
    tiles.placeOnRandomTile(章魚2, sprites.dungeon.hazardLava1)
})
info.onLifeZero(function () {
    game.over(false, effects.dissolve)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.floorDark1, function (sprite, location) {
    scene.setBackgroundColor(7)
    tiles.setTilemap(tilemap`層級9`)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精1, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(妖精2, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(妖精藍, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(妖精藍2, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(章魚, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(章魚2, sprites.castle.tileDarkGrass2)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`99金幣7`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`69地圖7`)
    tiles.placeOnRandomTile(mySprite, assets.tile`myTile11`)
    tiles.placeOnRandomTile(妖精1, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍, assets.tile`myTile3`)
    tiles.placeOnRandomTile(妖精藍2, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚, assets.tile`myTile3`)
    tiles.placeOnRandomTile(章魚2, assets.tile`myTile3`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`珍珠`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`主要地圖 金幣`)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.oceanDepths9)
    妖精1.setPosition(73, 195)
    妖精2.setPosition(43, 152)
    妖精藍.setPosition(248, 23)
    妖精藍2.setPosition(229, 10)
    章魚.setPosition(110, 200)
    章魚2.setPosition(120, 250)
    game.splash("阿阿阿", "我感到生命快要透支")
    pause(100)
    game.splash("但也感受到", "我的法力比以前還要強大很多")
    pause(100)
    game.splash("這代價..", "我要想辦法把生命補回來")
    pause(100)
    game.splash("我想到了家族", "秘密的辦法")
    pause(100)
    game.splash("可以補血的辦法", "太好了")
    pause(100)
    game.splash("我記得是要", "跳兩下 蹲兩下 ")
    pause(100)
    game.splash("我記得是要", "往左走兩步 往右走3步")
    pause(100)
    game.splash("往左攻擊兩次", "往右攻擊3次")
    info.changeScoreBy(500)
    info.changeLifeBy(-500)
})
controller.combos.attachCombo("uuddllrrraabbb", function () {
    mySprite.say("我是村西透", 500)
    animation.runImageAnimation(
    mySprite,
    assets.animation`myAnim`,
    500,
    false
    )
    info.changeLifeBy(100)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`鑽石傳送們`, function (sprite, location) {
    scene.setBackgroundColor(7)
    tiles.setTilemap(tilemap`層級7`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚2, sprites.swamp.swampTile2)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`告示牌2`, function (sprite, location) {
    game.splash("你來了阿", "你要的東西在前面")
    mySprite.say("怪怪的", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖3`, function (sprite, location) {
    mySprite.setImage(assets.image`wizard`)
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d20`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級8`)
    tiles.placeOnRandomTile(mySprite, sprites.castle.tileDarkGrass2)
    tiles.placeOnRandomTile(妖精1, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(妖精藍2, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚, sprites.swamp.swampTile2)
    tiles.placeOnRandomTile(章魚2, sprites.swamp.swampTile2)
})
scene.onOverlapTile(SpriteKind.Player, sprites.vehicle.roadTurn2, function (sprite, location) {
    mySprite.setImage(assets.image`wizard`)
    mySprite.say("呼 中了法術..", 500)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`告示牌1`, function (sprite, location) {
    game.splash("你來了阿", "你要的東西在前面")
    mySprite.say("嗯?", 200)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`告示牌10`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`cup2`, function (sprite, location) {
    info.changeScoreBy(1)
    tiles.setTileAt(location, assets.tile`transparency16`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`終極69`, function (sprite, location) {
    game.splash("你來了阿", "我等你很久了")
    pause(100)
    game.splash("勇者", "你要的東西在這裡")
    pause(100)
    game.splash("好好挑吧", "注意顏色或運氣")
    pause(100)
    game.splash("走吧走吧", "掰掰")
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`d5`, function (sprite, location) {
    tiles.setTilemap(tilemap`主要地圖 杯子`)
    scene.setBackgroundColor(15)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.oceanDepths9)
    info.changeLifeBy(102)
    game.splash("這鑽石得魔力", "居然可以看到我心")
    pause(100)
    game.splash("顏色變成了我愛人最愛的顏色", "深不可測的力量")
    妖精1.setPosition(73, 195)
    妖精2.setPosition(43, 152)
    妖精藍.setPosition(248, 23)
    妖精藍2.setPosition(229, 10)
    章魚.setPosition(110, 200)
    章魚2.setPosition(120, 250)
    info.changeLifeBy(400)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`cup陷阱`, function (sprite, location) {
    info.changeLifeBy(-1)
    tiles.setTileAt(location, assets.tile`transparency16`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`ten2`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級4`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.dungeon.hazardHole)
    tiles.placeOnRandomTile(妖精2, sprites.dungeon.hazardHole)
    tiles.placeOnRandomTile(妖精藍, sprites.dungeon.hazardHole)
    tiles.placeOnRandomTile(妖精藍2, sprites.dungeon.hazardHole)
    tiles.placeOnRandomTile(章魚, sprites.dungeon.hazardHole)
    tiles.placeOnRandomTile(章魚2, sprites.dungeon.hazardHole)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`69地圖5`, function (sprite, location) {
    scene.setBackgroundColor(15)
    tiles.setTilemap(tilemap`層級6`)
    tiles.placeOnRandomTile(mySprite, assets.tile`磚塊`)
    tiles.placeOnRandomTile(妖精1, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(妖精藍2, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚, sprites.builtin.forestTiles0)
    tiles.placeOnRandomTile(章魚2, sprites.builtin.forestTiles0)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-0.1)
})
let projectile: Sprite = null
let 章魚2: Sprite = null
let 章魚: Sprite = null
let 妖精藍2: Sprite = null
let 妖精藍: Sprite = null
let 妖精2: Sprite = null
let 妖精1: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundImage(assets.image`怪盜團`)
pause(2000)
game.splash("", "我的名子是村西透")
pause(100)
game.splash("接下來", "我會跟你講我來這裡的目的")
pause(100)
game.splash("我渴望力量", "我渴望成為過去未來")
pause(100)
game.splash("最強的", "魔法師")
pause(100)
game.splash("所以我來到", "傳說藏有5個秘寶的地方")
pause(100)
game.splash("我要來盜取秘寶", "成為最強大的法師")
pause(100)
game.splash("看來要好好觀察地圖", "加油")
pause(100)
mySprite = sprites.create(assets.image`wizard`, SpriteKind.Player)
controller.moveSprite(mySprite, 102, 102)
scene.setBackgroundImage(assets.tile`myTile6`)
scene.setBackgroundColor(15)
tiles.setTilemap(tilemap`主要地圖 劍`)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.builtin.oceanDepths9)
info.setLife(1000)
妖精1 = sprites.create(assets.image`妖精`, SpriteKind.Enemy)
妖精1.setPosition(73, 195)
妖精2 = sprites.create(assets.image`妖精2`, SpriteKind.Enemy)
妖精2.setPosition(43, 152)
妖精藍 = sprites.create(assets.image`妖精藍`, SpriteKind.Enemy)
妖精藍.setPosition(248, 23)
妖精藍2 = sprites.create(assets.image`妖精藍0`, SpriteKind.Enemy)
妖精藍2.setPosition(229, 10)
章魚 = sprites.create(assets.image`章魚2`, SpriteKind.Enemy)
章魚.setPosition(110, 200)
章魚2 = sprites.create(assets.image`章魚3`, SpriteKind.Enemy)
章魚2.setPosition(120, 250)
game.onUpdateInterval(2000, function () {
    if (章魚2.vx == 50) {
        章魚2.setVelocity(-50, 0)
    } else {
        章魚2.setVelocity(50, 0)
    }
})
game.onUpdateInterval(1000, function () {
    if (妖精2.vy == 30) {
        妖精2.setVelocity(0, -30)
    } else {
        妖精2.setVelocity(0, 30)
    }
})
game.onUpdateInterval(1000, function () {
    if (章魚.vy == 30) {
        章魚.setVelocity(0, -30)
    } else {
        章魚.setVelocity(0, 30)
    }
})
game.onUpdateInterval(500, function () {
    if (妖精1.vx == -50) {
        妖精1.setVelocity(50, 0)
    } else {
        妖精1.setVelocity(-50, 0)
    }
})
